### ISSUE TITLE
Some waveform peaks have negative values

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-api#575]
## Description

The frontend expects peaks to be in range of [0..1], however, some peaks returned from the API can have negative values.

## Reproduction

1. Go to https://api.openverse.engineering/v1/audio/727b9979-98f1-4604-9097-0a8b6fa68f2e/
2. Look at the last values of the long array.
3. See error: `...-0.00036,-0.00099,-0.00162,0.00012,0.0]}`

## Expectation

All the peaks should be in [0..1] range.

## Additional context

We could use a hack to fix this on the front end by setting negative values to 0 in the mean time, but the solution should be on the API side.
Could this possibly be some leftovers from the mock waveform data?
## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by dhruvkb** [comment]
It was inferred from the `audiowaveform` library output that it returns an alternating sequence of positive and negative amplitudes. 

https://github.com/WordPress/openverse-api/blob/4b775952bd3b78ab017f83602225d728d9df39f7/api/catalog/api/utils/waveform.py#L90-L93

But given that it was inferred and not explicitly documented, we should add a floor of zero during normalisation.

The alternative solution (which makes sense in order to avoid re-generating waveforms for all tracks) is to set this floor on the frontend. In any case the negative amplitudes are very very close to zero (I'm presuming rounding errors in the `audiowaveform` library) so manipulating them to zero would not be cheating.
