### ISSUE TITLE
Filtering by extension for audio doesn't work as expected

### ISSUE THREAD

**Issue by obulat** [WordPress/openverse-api#615]
## Problem

When you filter audio search by extension, you don't get results that you would expect. Only `mp3` category returns any results.

## Description

To get the audio extension field in ElasticSearch, we use the URL's last part.
https://github.com/WordPress/openverse-api/blob/5c9b654a9e3ab55932de42aa76ae2c17f5e85d1d/ingestion_server/ingestion_server/elasticsearch_models.py#L136-L144

This doesn't work well for audio because many URLs don't have an extension at all. Fortunately, most of the audio files should have the `filetype` attribute saved in the database, so we could use that as the `extension` value.

Marking this as high priority because having a category filter in the UI that is not working properly is confusing for the users.

## Alternatives

Not really alternative, but additional solutions would be to use the extensions of the `alt_files` in addition to the main file extension.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

**Comment by sarayourfriend** [comment]
@obulat This makes me feel doubly that we should be mapping file extensions on ingestion, in the catalog, rather than trying to derive it in the API and/or the frontend. Otherwise our ES logic will become massively complicated, trying to map individual provider quirks for showing the file format per result...

During ingestion we could at least make a HEAD request for the providers that we don't know for sure what the file type is and use the content-type header as a mime-type maybe?

Anyway, it seems like the place to normalize data is in ingestion rather than further down the data pipeline (where it will probably get duplicated between API and frontend).

**Comment by obulat** [comment]
I agree that we should get the filetype on ingestion.
However, because we have `alt_files`, we also need to decide whether we want to add some logic in the ES, too. Or we can say that we only use the main file's filetype (extension), and do not include the items with the selected extension only in the `alt_files`.
For example, if the file is `galah.ogg`, but has `galah.mp3` in the `alt_files`, do we show it when we search for `mp3` 'galah' files? This would require some ES logic, I suppose.

**Comment by sarayourfriend** [comment]
I think we'd _only_ filter on the downloadable file types, right? So basically only filter on the file types of `alt_files`. Otherwise we're misleading someone in the example you gave if we filter it as an ogg file but they can only download an mp3.

We don't currently offer the preview audio as a download option (unless there are no alt_files OR if that file is already included in alt files). This is because some providers require logging in to get the proper audio download and we wanted to respect that, so we partition the preview audio as a totally separate thing.

Ideally we'd never have an empty alt_files for any provider (and probably should rename `alt_files` to like `downloadable_files` or something clearer, they're not "alternatives" in the case for audio, they are the actual downloadable files and the preview is "just" a preview, for which quality and file type information should be completely ignored from a consumer perspective).

At least that's my understanding of it. The audio alt files stuff has been such a pain and it feels like we could do with taking a step back and thinking of it holistically, from the top to the bottom of the stack to make sure the usage and data that we're collecting is clear and fulfills all the requirements necessary. We keep coming back to confusions about the alt files and how they work and how we're meant to work with them, it seems clear to me that we've missed something in defining the requirements for this.

**Comment by sarayourfriend** [comment]
cc @WordPress/openverse-developers because this conversation is a lot bigger than just me and Olga :slightly_smiling_face:

**Comment by zackkrida** [comment]
Yeah, the name `alt_files` has likely been a source of the confusion. `downloadable_files` or simply `files` would be much clearer. And agreed, the format of the _preview_ shouldn't be considered in the filtering. 

> We don't currently offer the preview audio as a download option (unless there are no alt_files OR if that file is already included in alt files). This is because some providers require logging in to get the proper audio download and we wanted to respect that, so we partition the preview audio as a totally separate thing.

It might help to _only_ use `alt_files` for the download options in the frontend, and add the preview audio to `alt_files` at the Catalog level if there are no `alt_files`. Then we don't have to fiddle with as much on the frontend: The download button simply lists all `alt_files` instead of building it's own list with the preview file.

**Comment by dhruvkb** [comment]
The main reason for the differentiation between the main file and `alt_files` was that the main file is supposed to be the best quality while the `alt_files` are other lower quality/smaller sizes. This is similar to [how Wikimedia Commons shows "Original file" and "Other resolutions"](https://commons.wikimedia.org/wiki/File:Pacific_Ocean_laea_location_map.svg#mw-jump-to-license).

**Comment by AetherUnbound** [comment]
> The main reason for the differentiation between the main file and `alt_files` was that the main file is supposed to be the best quality while the `alt_files` are other lower quality/smaller sizes. This is similar to [how Wikimedia Commons shows "Original file" and "Other resolutions"](https://commons.wikimedia.org/wiki/File:Pacific_Ocean_laea_location_map.svg#mw-jump-to-license).

That's super helpful context, thank you! I think our use case ultimately ends up being different from Wikimedia Commons, since the first file folks encounter is the preview rather than the original file. To sum up the discussion here, I think the following might be the best course of action:
* Rename `alt_files` to `downloadable_files`
* Add steps in the provider scripts that:
  * Capture extension information for each of the `downloadable_files`
  * Add the preview file information to `downloadable_files` iff no other `downloadable_files` exist
* Add the extensions as a list to the audio Elasticsearch model so they can be used in searches

Does that capture everything? Anything I'm missing or anything else we should consider?

**Comment by sarayourfriend** [comment]
+1 to your point about our usage being different than WM Commons. We don't control the full stack of information or policies that all providers give us and our users access to so our data model needs to be more flexible/specific than WM's.

> Rename alt_files to downloadable_files

Note that this will require a new API version as it is a non-backwards compatible breaking change. Unfortunately in a versioned API you just have to live with bad names forever until you are ready to cut a new version (or else break the implicit contract of the version prefix and lose trust from consumers of the API). `alt_files` as a property name on the API response is the smallest problem here so personally I'm fine leaving out changing it until we're ready to work on cutting a new API version. Solving the problems with the _data_ in it (the other part of your suggested approach) is more important.

We could send both alt_files and downloadable_files, but then we're really making a bigger API response for little gain.

The rest sounds great though, Madison.

**Comment by AetherUnbound** [comment]
Ah jeez, I forgot about API versioning! :confounded: We'd also need to consider backfills, particularly for Wikimedia. Though I don't think we're losing out on any _current_ functionality if we just rename the field, so there may not be as much urgency there.

**Comment by zackkrida** [comment]
Yeah I'm fine with preserving the user-facing `alt_files` names. I wonder how we could add documentation like 'this will be renamed to {x} in a future release. Could we mark the current field as deprecated with a note, or something?

**Comment by sarayourfriend** [comment]
I don't think it's necessary to pre-emptively document the differences between current and future (still theoretical) API versions. The field name will never change in the version so for people who are not interested in new versions of the API it doesn't matter. For everyone else (who are keeping up with changelogs) they will be notified when it's available and when they upgrade to the new endpoint version.

**Comment by krysal** [comment]
There was certainly a confusion somewhere along the way in that a difference between preview files and downloadable files was assumed to be the foundation of the audio model, but actually, the audio table was conceived as Dhruv mentioned:

> the main file is supposed to be the best quality while the alt_files are other lower quality/smaller sizes

The main audio is in most cases a full audio track, not a preview. If I recall correctly, we were only using previews as a workaround in the case of Freesound to be able to reproduce something in Openverse, because of its API limitation that requires OAuth authentication to access a full audio track. We don't store any `alt_files` from Wikimedia or Jamendo either. So I believe we shouldn't base the model on whether the audio can be downloaded or not, since it's even possible that we remove the download button in the future and that can make the model more flexible.

That said I agree that we should get extension/file type, and actually _ALL_ the info needed on ingestion, including the waveform since we are here.

**Comment by AetherUnbound** [comment]
Here's a snapshot of our data:
![image](https://user-images.githubusercontent.com/10214785/163046828-636448f5-cfae-45b4-881c-cf9ee3ee13e5.png)

Summarizing [some discussion from our public Slack](https://wordpress.slack.com/archives/C02012JB00N/p1649776492982129):
1. We'd still like to rename `alt_files` to `downloadable_files`, as the name feels more appropriate for our intended usecase.
2. In cases where `downloadable_files` is not null, the `url` field semantically represents the **preview URL** and may not actually correspond to a downloadable file.
3. The extension logic would be as follows:
    1. If a record has no `downloadable_files`, the `url` and `filetype` fields _on the record_ represent the downloadable file
    1. If a record has `downloadable_files`, only the entries within the `downloadable_files` array represent downloadable files

The question we have open is whether we want that logic encapsulated in code, or removed entirely by populating the `downloadable_files` array with the existing record info if it is empty (as described above). Duplicating the data within the record would certainly be easier, but I'm concerned at how a size increase would affect indexing & speed. It's possible that we could add this logic into the media type views - we only keep one copy of the data, but when the view is materialized it performs some JSON manipulation to add any missing info to `downloadable_files`.

It may also be straightforward to extract the information we need in the Elasticsearch models. I suspect that would be pretty easy, but I'd need to take a look at the codebase. That to say, I'll attempt the ES path while also trying to get a better understanding of how data duplication might affect our already large database.

**Comment by sarayourfriend** [comment]
> We'd still like to rename alt_files to downloadable_files, as the name feels more appropriate for our intended usecase.

Just want to re-iterate, we can rename this internally but the external name for this field will have to remain `alt_files` as long as we're still on the v1 of the audio api endpoint.

> In cases where downloadable_files is not null

Kind of a nit, but just want to be sure to cover the edge case, downloadable_files could also be _empty_ otherwise (length == 0). I don't know if we have actual data that looks like that though.

The plan sounds good though! Thank you for summarizing the discussion from slack.

**Comment by AetherUnbound** [comment]
I am not actively on it @krysal, please feel free to take it if you have time!

**Comment by obulat** [comment]
I wonder if it would make sense to have the following columns:
- `playable_audio` - this can be either the main, highest quality audio, or, if it can't be played by our front end without authentication, some preview file that can. So, it will be the `hq mp3` preview for Freesound, and the main files for Wikimedia and Jamendo. The main criteria for this file is playability without auth. I'm not sure if we want to include this file's extension in the extension filters.
- `downloadable_files`( or`alt_files` externally so as we don't break the API compatibility) - all high-quality files (not previews) that can be downloaded from the provider sites (even if they require authentication). The `playable_audio` can also be duplicated in this list, and it can also be the only available `downloadable_file`. This will mean duplication, but since we cannot assume that all `playable_audio` files are downloadable, it has to be this way.

And no `main` audio, because it is confusing as it currently serves two purposes, depending on the provider: playable audio or the audio of the highest quality. Or we could duplicate once again here, using the highest-quality `downloadable` audio as the `main` one.

Actually, we might even say that our `main` audio is the `playable` audio only, so if API users want the highest quality file, they would need to select one of the `downloadable_files`.
As for the `extensions` to add to the filters that we discuss in #769, I'm not quite sure. On the one hand, I would prefer to only index the `downloadable_files`. On the other, it might be confusing when you can see on the page that an `mp3` audio is playing, but it's not returned as a result for an `mp3` extension filter.
