### ISSUE TITLE
Duration filter is inaccurate

### ISSUE THREAD

**Issue by AetherUnbound** [WordPress/openverse-api#652]
## Description

We have duration filters defined in our Elasticsearch models:

https://github.com/WordPress/openverse-api/blob/a7955c86d43bff504e8d41454f68717d79dd3a44/ingestion_server/ingestion_server/elasticsearch_models.py#L307-L309

Unfortunately, duration does not seem to be accurate (these results are several hours long but appear in all available filters):
* https://api.openverse.engineering/v1/audio/?q=deuteronomy&duration=short
* https://api.openverse.engineering/v1/audio/?q=deuteronomy&duration=long

It seems like this may be due to the nature of the `get_duration` function on the model:

https://github.com/WordPress/openverse-api/blob/a7955c86d43bff504e8d41454f68717d79dd3a44/ingestion_server/ingestion_server/elasticsearch_models.py#L340

It may also be due to an order of magnitude mismatch (e.g. expecting ms when it's actually seconds).

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

**Comment by sarayourfriend** [comment]
The durations in the catalog, at least for Wikimedia, are in seconds. You can see an example response in this comment (expand the Response JSON section): https://github.com/WordPress/openverse-catalog/issues/445#issuecomment-1095548184

I'm sure we'll have variation here between provider, if not now then eventually. It'd be nice if the field was named `duration_sec` or `duration_ms` (whichever we land on) so that it's clearer for the consumer :slightly_smiling_face: 

That withstanding, I think to fix this we should:

1. Confirm that our current providers all use seconds
2. If they don't, then normalize the data in the catalog (either to seconds or whatever we want to use)
3. After they're all using the same unit, update the query configuration if necessary

**Comment by obulat** [comment]
We did add conversion to milliseconds to providers who use seconds (apparently, it's all of them 😆 ):
    
https://github.com/WordPress/openverse-catalog/blob/e98cf7993b5ebdb6f9e4d0b3117a3e4b5ffb182a/openverse_catalog/dags/providers/provider_api_scripts/wikimedia_commons.py#L316-L317

https://github.com/WordPress/openverse-catalog/blob/e98cf7993b5ebdb6f9e4d0b3117a3e4b5ffb182a/openverse_catalog/dags/providers/provider_api_scripts/freesound.py#L178

https://github.com/WordPress/openverse-catalog/blob/e98cf7993b5ebdb6f9e4d0b3117a3e4b5ffb182a/openverse_catalog/dags/providers/provider_api_scripts/jamendo.py#L203-L204

**Comment by sarayourfriend** [comment]
Well then it's not a units problem, that hopefully means it doesn't require updating the data to fix it :stuck_out_tongue:
